# Generated by Django 5.2.16 on 2026-07-11 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Google Gemini', max_length=100, verbose_name='Название')),
                ('model_name', models.CharField(default='gemini-2.5-flash', max_length=100, verbose_name='Модель')),
                ('api_key_encrypted', models.TextField(blank=True, editable=False, verbose_name='API-ключ (зашифрован)')),
                ('temperature', models.FloatField(default=0.1, verbose_name='Температура')),
                ('timeout_seconds', models.PositiveIntegerField(default=180, verbose_name='Таймаут, секунд')),
                ('system_prompt', models.TextField(default='Ты — эксперт по распознаванию официальных документов. Извлекай только подтверждённые сканом данные, переводи текстовые значения на русский язык и не выдумывай отсутствующие сведения.', verbose_name='Общая инструкция агенту')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'настройка ИИ',
                'verbose_name_plural': 'настройки ИИ',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='templates/', verbose_name='DOCX с переменными Jinja')),
                ('extraction_prompt', models.TextField(blank=True, help_text='Например: формат дат, особенности печатей, правила транслитерации.', verbose_name='Дополнительная инструкция для этого шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для загрузки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'шаблон документа',
                'verbose_name_plural': 'шаблоны документов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Название документа')),
                ('source_pdf', models.FileField(upload_to='scans/%Y/%m/', verbose_name='Скан PDF')),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('processing', 'Обрабатывается'), ('review', 'На проверке'), ('ready', 'Готов'), ('error', 'Ошибка')], default='uploaded', max_length=20, verbose_name='Статус')),
                ('extracted_data', models.JSONField(blank=True, default=dict, verbose_name='Результат ИИ')),
                ('edited_data', models.JSONField(blank=True, default=dict, verbose_name='Отредактированные данные')),
                ('generated_docx', models.FileField(blank=True, upload_to='results/%Y/%m/', verbose_name='Готовый DOCX')),
                ('generated_pdf', models.FileField(blank=True, upload_to='results/%Y/%m/', verbose_name='PDF для предпросмотра')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='studio.documenttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'обрабатываемый документ',
                'verbose_name_plural': 'обрабатываемые документы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя Jinja-переменной')),
                ('label', models.CharField(max_length=180, verbose_name='Название поля')),
                ('ai_instruction', models.TextField(blank=True, verbose_name='Что искать на скане')),
                ('translate_to_russian', models.BooleanField(default=True, verbose_name='Перевести на русский')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательное')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='studio.documenttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'переменная шаблона',
                'verbose_name_plural': 'переменные шаблона',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('template', 'name')},
            },
        ),
    ]
