# Generated by Django 5.2.16 on 2026-07-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='model_name',
            field=models.CharField(default='gemini-3.5-flash', max_length=100, verbose_name='Модель'),
        ),
    ]
